---
- hosts: prod
  become: yes
  user: root
  roles:
    - common
    - nginx
    - mysql
    - php
    - composer
    - letsencrypt
    - phpmyadmin
    - wordpress
    - opendkim
    - postfix
    - dovecot
    - roundcube
    - swap