---
- name: Write swapfile
  command: fallocate -l {{ swapfile_size }} {{ swapfile_location }} creates={{ swapfile_location }}
  register: write_swapfile
  when: swapfile_size != false

- name: Set swapfile permissions
  file: 
    path: "{{ swapfile_location }}"
    mode: 600
  when: swapfile_size != false

- name: Create swapfile
  command: mkswap {{ swapfile_location }}
  environment:
    PATH: "{{ (ansible_env|default({})).PATH|default('') }}:/usr/local/sbin:/usr/sbin:/sbin"
  register: create_swapfile
  when: swapfile_size != false and write_swapfile.changed

- name: Enable swapfile
  command: swapon {{ swapfile_location }}
  environment:
    PATH: "{{ (ansible_env|default({})).PATH|default('') }}:/usr/local/sbin:/usr/sbin:/sbin"
  when: swapfile_size != false and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  mount:
    name: none
    src: "{{ swapfile_location }}"
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
  when: swapfile_size != false

- name: configure vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swapfile_swappiness }}"
    reload: true
    state: present
  when: swapfile_swappiness is defined

- name: configure vm.vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure }}"
    reload: true
    state: present
  when: swapfile_vfs_cache_pressure is defined
  tags:
    - configuration
    - swapfile
    - swapfile-vm-vfs-cache-pressure