---

- name: check if DB exists
  shell: mysql --user={{ db_username }} --password={{ db_password }} -e 'SHOW DATABASES;' | grep -c {{ mail_db_name }}
  register: dbstatus
  failed_when: dbstatus.rc == 2

- name: Create database
  mysql_db: 
    name: "{{ mail_db_name }}"
    encoding: utf8 
    collation: utf8_general_ci 
    state: present 
    login_host: "{{ db_host }}"
    login_user: "{{ db_root_username }}"
    login_password: "{{ db_root_password }}"
  when: dbstatus.stdout == "0"

- name: Create application user in the database
  mysql_user: 
    name: "{{ mail_db_user }}"
    password: "{{ mail_db_pass }}"
    append_privs: true
    priv: "{{ mail_db_name }}.*:ALL"
    state: present
    login_host: "{{ db_host }} "
    login_user: "{{ db_root_username }}"
    login_password: "{{ db_root_password }}"

- name: check if tables exists
  shell: mysql --user={{ mail_db_user }} --password={{ db_password }} --database={{ mail_db_name }} -e 'CREATE TABLE IF NOT EXISTS {{ item }};'
  with_items:
    - "`virtual_domains` (`id` int(11) NOT NULL auto_increment, `name` varchar(50) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8"
    - "`virtual_users` (`id` int(11) NOT NULL auto_increment, `domain_id` int(11) NOT NULL, `password` varchar(106) NOT NULL, `email` varchar(100) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `email` (`email`), FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8"
    - "`virtual_aliases` (`id` int(11) NOT NULL auto_increment,`domain_id` int(11) NOT NULL,`source` varchar(100) NOT NULL,`destination` varchar(100) NOT NULL,PRIMARY KEY (`id`),FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8"
  
- name: install postfix
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - postfix
    - postfix-mysql
    - postfix-policyd-spf-python 
    - postfix-pcre
  
- name: add config files
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 644
  with_items:
    - {src: 'main.cf.j2',dest: '/etc/postfix/main.cf'}
    - {src: 'master.cf.j2',dest: '/etc/postfix/master.cf'}
    - {src: 'mysql-virtual-alias-maps.cf.j2',dest: '/etc/postfix/mysql-virtual-alias-maps.cf'}
    - {src: 'mysql-virtual-mailbox-domains.cf.j2',dest: '/etc/postfix/mysql-virtual-mailbox-domains.cf'}
    - {src: 'mysql-virtual-mailbox-maps.cf.j2',dest: '/etc/postfix/mysql-virtual-mailbox-maps.cf'}
  notify:
    - restart postfix
