---
- name: Install dbconfig-common
  apt: 
    pkg: dbconfig-common 
    state: latest 
    install_recommends: no

- name: Pre-configure PHPMyAdmin database
  template: 
    src: roles/phpmyadmin/templates/phpmyadmin.conf.j2
    dest: /etc/dbconfig-common/phpmyadmin.conf
    owner: root 
    group: root 
    mode: 0600
            
- name: Create database for PHPMyAdmin
  mysql_db: 
    name: "{{ phpmyadmin_control_database | default('phpmyadmin') }}" 
    state: present
  register: phpmyadmin_database

- name: Create PHPMyAdmin control user
  mysql_user: 
    name: "{{ phpmyadmin_control_user | default('phpmyadmin') }}"
    state: present
    password: "{{ phpmyadmin_control_password }}" 
    priv: "{{ phpmyadmin_control_database | default('phpmyadmin') }}.*:ALL"

- name: download phpmyadmin
  git: 
    repo: "{{ phpmyadmin_repo }}" 
    depth: 1 
    version: STABLE 
    dest: /var/www/phpmyadmin 
    force: yes
  register: phpmyadminDownloaded
  
- name: install libs via composer 
  command: composer install -d /var/www/phpmyadmin

- name: add phpmyadmin virtualhost
  when: phpmyadminDownloaded|success
  template: 
    src: roles/phpmyadmin/templates/phpmyadmin.j2 
    dest: /etc/nginx/sites-available/phpmyadmin mode=0640
  
- name: add phpmyadmin virtualhost
  when: phpmyadminDownloaded|success
  template: 
    src: roles/phpmyadmin/templates/config.sample.inc.php.j2 
    dest: /var/www/phpmyadmin/config.inc.php

- name: enable phpmyadmin
  when: phpmyadminDownloaded|success
  file: 
    src: /etc/nginx/sites-available/phpmyadmin 
    dest: /etc/nginx/sites-enabled/phpmyadmin 
    state: link
  notify:
    - reload nginx